"""Intital Migration

Revision ID: 9e529497a68e
Revises: e41aa41f14c5
Create Date: 2026-07-26 16:47:14.682397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9e529497a68e'
down_revision: Union[str, Sequence[str], None] = 'e41aa41f14c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
