"""add fired flag to reminders

Revision ID: db95c8f20d0b
Revises: 16fe6f29bc4c
Create Date: 2026-08-14 07:47:18.194056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db95c8f20d0b'
down_revision: Union[str, Sequence[str], None] = '16fe6f29bc4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('fired', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'fired')
    # ### end Alembic commands ###
